export const DECLINE_DOMAINS = [
  { key: "nutritional", label: "Nutritional / Weight", placeholder: "Describe changes in oral intake, appetite, weight loss, tube feeding tolerance, or swallowing since last certification. Include specific weights and percentages if available." },
  { key: "functional", label: "Functional / ADL Dependence", placeholder: "Describe changes in ability to perform activities of daily living since last certification. Note increase in assist level required." },
  { key: "cognitive", label: "Cognitive / Behavioral", placeholder: "Describe changes in cognition, orientation, memory, communication, or behavior since last certification." },
  { key: "mobility", label: "Mobility / Falls", placeholder: "Describe changes in ambulation, transfers, bed mobility, or fall frequency since last certification. Include number of falls this period." },
  { key: "cardiopulmonary", label: "Cardiopulmonary / Respiratory", placeholder: "Describe changes in dyspnea, oxygen requirements, edema, or cardiac symptoms since last certification." },
  { key: "skin", label: "Skin / Integumentary", placeholder: "Describe any new or worsening wounds, pressure injuries, or skin breakdown since last certification." },
  { key: "pain", label: "Pain / Symptom Burden", placeholder: "Describe changes in pain severity, frequency, or character since last certification." },
  { key: "sleep", label: "Sleep / Energy / Fatigue", placeholder: "Describe changes in sleep pattern, energy level, and fatigue since last certification." },
  { key: "psychosocial", label: "Psychosocial / Family", placeholder: "Describe changes in patient mood, coping, or engagement since last certification." },
];

export function buildRNRecertSystem(inputs) {
  const domainText = DECLINE_DOMAINS
    .filter(d => inputs[d.key]?.trim())
    .map(d => d.label.toUpperCase() + ":\n" + inputs[d.key])
    .join("\n\n");
  return "You are a clinical documentation specialist generating a hospice RN Recertification Narrative.\n\nRULES:\n- Third-person clinical narrative. NEVER use I.\n- Preserve ALL numbers, measurements, weights, dates EXACTLY.\n- Never fabricate.\n- Interval framing MANDATORY throughout - use since last certification, this certification period, compared to prior period.\n- Quantify decline wherever possible.\n- No disclaimers. Clean clinical text only.\n- Do NOT include hospice eligibility conclusions.\n- ALL CAPS section headers for each domain.\n- Only include sections with data provided.\n\nPATIENT INFORMATION:\nDiagnosis: " + (inputs.diagnosis || "Not provided") + "\nPatient Identifier: " + (inputs.patientId || "Not provided") + "\nCertification Period: " + (inputs.certPeriod || "Not provided") + "\nLast Recert Baseline: " + (inputs.lastBaseline || "Not provided") + "\n\nOBJECTIVE DATA:\nFAST: " + (inputs.fast || "Not provided") + "\nPPS: " + (inputs.pps || "Not provided") + "\nKPS: " + (inputs.kps || "Not provided") + "\nWeight / Trend: " + (inputs.weight || "Not provided") + "\nVitals: " + (inputs.vitals || "Not provided") + "\n\nDECLINE DOMAIN ASSESSMENTS:\n" + (domainText || "No domain data provided");
}

export function buildMDRecertSystem(inputs, rnNarrative) {
  return "You are a hospice medical director generating a Physician Recertification Note.\n\nRULES:\n- Authoritative physician voice. Third-person. Never I.\n- Preserve ALL numbers, measurements, dates EXACTLY.\n- Never fabricate.\n- This is a DECLINE DELTA document - focus on what has worsened this period.\n- No disclaimers. Clean clinical text only.\n\nSTRUCTURE:\n1. PATIENT IDENTIFICATION - one sentence: identifier, diagnosis, certification period.\n2. DECLINE SUMMARY - bulleted list by domain. Each bullet states what declined and by how much.\n3. OBJECTIVE FUNCTIONAL DATA - FAST, PPS%, KPS%, weight, vitals. All exact.\n4. CLINICAL IMPRESSION - two to three sentences synthesizing decline trajectory.\n5. RECERTIFICATION STATEMENT - close with: Based on the clinical findings documented above, " + (inputs.patientId || "this patient") + " remains appropriate for hospice recertification with a life expectancy of less than six months if the terminal illness runs its expected course.\n\nPATIENT INFORMATION:\nDiagnosis: " + (inputs.diagnosis || "Not provided") + "\nPatient Identifier: " + (inputs.patientId || "Not provided") + "\nCertification Period: " + (inputs.certPeriod || "Not provided") + "\n\nPHYSICIAN ADDITIONAL OBSERVATIONS:\n" + (inputs.mdObservations || "None provided") + "\n\nFACE-TO-FACE ENCOUNTER:\n" + (inputs.f2fCompleted ? "Completed on " + (inputs.f2fDate || "date not provided") + ". Findings: " + (inputs.f2fFindings || "not documented") : "Not completed this period") + "\n\nRN RECERTIFICATION NARRATIVE:\n" + rnNarrative;
}
